### ISSUE TITLE
Website enhancements

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2824]
As discussed during the online session of the sprint today, here are some possible directions and action points for improving the current website. 
I tried to translate what we discussed in a concise way but I might have misunderstood/forgotten some points... Please comment and correct me if that's the case.

**Searching**
- [x] Remove duplicate search-bar (See #1816)
- [x] Improve the searching experience when using the search-bar

**Design and structure**
- [x] Improve the design (See #813)
- [x] Redesign the landing page to ease access to resources
- [x] When browsing the API it is not clear where you are (we should consider having a tree on a left or something alike)
- [x] Having a subset of chosen examples organized in an ordered list to quickly learn what nilearn does
- [ ] Better explanation of what nilearn does in comparison to other tools of the ecosystem? --> see https://github.com/nilearn/nilearn/issues/2828

**Interactivity**
- [x] Links to binders are at the end of the examples and difficult to find.
- [ ] You also have to know what binder is to click on these buttons.
- [x] Would be great to have a binder button at the root of the tutorials to just follow them along without having to start and quit at every example.

Please comment on this issue if you have ideas/suggestions/inputs regarding the current website.

**Comment by ymzayek** [comment]
I think we can close this one since a lot of the points might have been met with the merge of #3125. However, maybe some things can be carried over to a new issue if need be

**Comment by Remi-Gau** [comment]
probably worth revisiting this one and moving things we think are still worth doing to single issues.

**Comment by ymzayek** [comment]
> - Better explanation of what nilearn does in comparison to other tools of the ecosystem?

This is worth an issue as pointed out by @alexisthual 

Regarding Binder and interactivity, the last point is addressed as with the current setup all the notebooks are built and jupyterlab is used so you can easily navigate through all of them in the launched lab environment. We could add a sentence somewhere for people to know to look for the binder link and/or move it to the top if possible

**Comment by Remi-Gau** [comment]
> move it to the top if possible

that'd be preferable

**Comment by Remi-Gau** [comment]
- There is already an issue for https://github.com/nilearn/nilearn/issues/2828

So the only thing left for this issue is to better describe / advertise binder.

**Comment by Remi-Gau** [comment]
Possible option to make link to binder button more visible with explanations

https://github.com/sphinx-gallery/sphinx-gallery/issues/978
