### ISSUE TITLE
Roadmap 0.11.0

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3812]
To list issues to tackle for the next release.

**See [milestone](https://github.com/nilearn/nilearn/milestone/26)**

## Surface support

- [x] See meta-issue: #4027 

## Dropping python 3.8

- [x] update pyproject.toml
- [x] update CI
- [x] run `pre-commit run -a`

## Support python 3.13

- [x] update pyproject.toml
- [x] update CI

## Follow release protocol

- https://nilearn.github.io/stable/maintenance.html#how-to-make-a-release

**Comment by ymzayek** [comment]
We probably will also need to bump up versions of dependencies and deal with deprecations

**Comment by Remi-Gau** [comment]
> We probably will also need to bump up versions of dependencies and deal with deprecations

added a link to the release protocol that covers this.

**Comment by ymzayek** [comment]
Suggestion TODOs to add:
- [ ] Update python version for building dev docs
- [ ] Update _python_doc_base in conf.py

**Comment by Remi-Gau** [comment]
For reference: 

end of life for 3.8 and release of 3.13: https://devguide.python.org/versions/#status-of-python-versions

Given this and the discussion at the last dev meeting (yesterday), we should aim for a release of Nilearn 0.11.0 towards the end of October.

I have updated the [milestone for it](https://github.com/nilearn/nilearn/milestone/26) to contain only the REQUIRED features or bug fixes. Everything else should be considered nice to have.
