### ISSUE TITLE
[DOC] todo of missing default value in docstrings

### ISSUE THREAD

**Issue by mathdugre** [nilearn/nilearn#3865]
> [!TIP]
> # **💻 🍁  For the [hacktoberfest](https://hacktoberfest.com/) contributors 🍁 💻**
>
> Make sure to:
> - read our [contributing guidelines](https://nilearn.github.io/stable/development.html#contribution-guidelines)
>
> If this is your first time contributing to Nilearn, add your details in the [CITATION.cff file](https://github.com/nilearn/nilearn/blob/dcd92aa357ab3a751161aeea2edfa3a775ae644f/CITATION.cff#L42).
>
> For your pull request to be valid, you should add all the defaults value to one of the nilearn module listed below.
>

---

> [!NOTE] 
> Using the script added https://github.com/nilearn/nilearn_sandbox/pull/12, the following list of docstring default values was generated.
[missing_docstring_default.md](https://github.com/nilearn/nilearn/files/12134475/missing_docstring_default.md)

# List any pages that would be impacted.

## [nilearn/masking.py](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py)
[nilearn/masking.py::extrapolate_out_mask - **line: 91**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L91)
<br>Potential arguments to fix
- [ ] `iterations` `Default=1`

[nilearn/masking.py::compute_epi_mask - **line: 225**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L225)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`

[nilearn/masking.py::compute_multi_epi_mask - **line: 342**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L342)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`
- [ ] `threshold` `Default=0.5`

[nilearn/masking.py::compute_background_mask - **line: 435**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L435)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`

[nilearn/masking.py::compute_multi_background_mask - **line: 516**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L516)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`
- [ ] `threshold` `Default=0.5`
- [ ] `opening` `Default=2`

[nilearn/masking.py::compute_brain_mask - **line: 596**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L596)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`

[nilearn/masking.py::compute_multi_brain_mask - **line: 675**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L675)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`

[nilearn/masking.py::apply_mask - **line: 761**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L761)
<br>Potential arguments to fix
- [ ] `dtype` `Default='f'`

[nilearn/masking.py::apply_mask_fmri - **line: 814**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L814)
<br>Potential arguments to fix
- [ ] `ensure_finite` `Default=True`
- [ ] `smoothing_fwhm` `Default=None`
- [ ] `dtype` `Default='f'`

[nilearn/masking.py::unmask - **line: 929**](https://github.com/nilearn/nilearn/blob/main/nilearn/masking.py#L929)
<br>Potential arguments to fix
- [ ] `order` `Default='F'`

## [nilearn/signal.py](https://github.com/nilearn/nilearn/blob/main/nilearn/signal.py)
[nilearn/signal.py::butterworth - **line: 328**](https://github.com/nilearn/nilearn/blob/main/nilearn/signal.py#L328)
<br>Potential arguments to fix
- [ ] `copy` `Default=False`
- [ ] `padlen` `Default=None`
- [ ] `padtype` `Default='odd'`

[nilearn/signal.py::clean - **line: 543**](https://github.com/nilearn/nilearn/blob/main/nilearn/signal.py#L543)
<br>Potential arguments to fix
- [ ] `standardize` `Default='zscore'`

## [nilearn/reporting/glm_reporter.py](https://github.com/nilearn/nilearn/blob/main/nilearn/reporting/glm_reporter.py)
[nilearn/reporting/glm_reporter.py::make_glm_report - **line: 52**](https://github.com/nilearn/nilearn/blob/main/nilearn/reporting/glm_reporter.py#L52)
<br>Potential arguments to fix
- [ ] `display_mode` `Default=None`
- [ ] `min_distance` `Default=8.0`
- [ ] `title` `Default=None`

## [nilearn/reporting/get_clusters_table.py](https://github.com/nilearn/nilearn/blob/main/nilearn/reporting/get_clusters_table.py)
[nilearn/reporting/get_clusters_table.py::get_clusters_table - **line: 209**](https://github.com/nilearn/nilearn/blob/main/nilearn/reporting/get_clusters_table.py#L209)
<br>Potential arguments to fix
- [ ] `min_distance` `Default=8.0`

## [nilearn/mass_univariate/permuted_least_squares.py](https://github.com/nilearn/nilearn/blob/main/nilearn/mass_univariate/permuted_least_squares.py)
[nilearn/mass_univariate/permuted_least_squares.py::permuted_ols - **line: 302**](https://github.com/nilearn/nilearn/blob/main/nilearn/mass_univariate/permuted_least_squares.py#L302)
<br>Potential arguments to fix
- [ ] `output_type` `Default='legacy'`
- [ ] `masker` `Default=None`
- [ ] `random_state` `Default=None`
- [ ] `confounding_vars` `Default=None`

## [nilearn/datasets/atlas.py](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/atlas.py)
[nilearn/datasets/atlas.py::fetch_atlas_craddock_2012 - **line: 158**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/atlas.py#L158)
<br>Potential arguments to fix
- [ ] `grp_mean` `Default=True`
- [ ] `homogeneity` `Default=None`

[nilearn/datasets/atlas.py::fetch_atlas_smith_2009 - **line: 962**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/atlas.py#L962)
<br>Potential arguments to fix
- [ ] `dimension` `Default=None`

[nilearn/datasets/atlas.py::fetch_atlas_basc_multiscale_2015 - **line: 1361**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/atlas.py#L1361)
<br>Potential arguments to fix
- [ ] `resolution` `Default=None`

[nilearn/datasets/atlas.py::fetch_atlas_schaefer_2018 - **line: 2059**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/atlas.py#L2059)
<br>Potential arguments to fix
- [ ] `base_url` `Default=None`

## [nilearn/datasets/struct.py](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py)
[nilearn/datasets/struct.py::load_mni152_template - **line: 173**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L173)
<br>Potential arguments to fix
- [ ] `resolution` `Default=None`

[nilearn/datasets/struct.py::load_mni152_gm_template - **line: 238**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L238)
<br>Potential arguments to fix
- [ ] `resolution` `Default=None`

[nilearn/datasets/struct.py::load_mni152_wm_template - **line: 293**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L293)
<br>Potential arguments to fix
- [ ] `resolution` `Default=None`

[nilearn/datasets/struct.py::load_mni152_brain_mask - **line: 349**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L349)
<br>Potential arguments to fix
- [ ] `resolution` `Default=None`

[nilearn/datasets/struct.py::load_mni152_gm_mask - **line: 393**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L393)
<br>Potential arguments to fix
- [ ] `n_iter` `Default=2`
- [ ] `resolution` `Default=None`

[nilearn/datasets/struct.py::load_mni152_wm_mask - **line: 446**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L446)
<br>Potential arguments to fix
- [ ] `n_iter` `Default=2`
- [ ] `resolution` `Default=None`

[nilearn/datasets/struct.py::fetch_icbm152_brain_gm_mask - **line: 500**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L500)
<br>Potential arguments to fix
- [ ] `n_iter` `Default=2`

[nilearn/datasets/struct.py::fetch_oasis_vbm - **line: 615**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/struct.py#L615)
<br>Potential arguments to fix
- [ ] `n_subjects` `Default=None`

## [nilearn/datasets/neurovault.py](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/neurovault.py)
[nilearn/datasets/neurovault.py::fetch_neurovault - **line: 2483**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/neurovault.py#L2483)
<br>Potential arguments to fix
- [ ] `data_dir` `Default=None`
- [ ] `mode` `Default='download_new'`
- [ ] `image_filter` `Default=_empty_filter`
- [ ] `collection_filter` `Default=_empty_filter`
- [ ] `max_images` `Default=_DEFAULT_MAX_IMAGES`

[nilearn/datasets/neurovault.py::fetch_neurovault_ids - **line: 2721**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/neurovault.py#L2721)
<br>Potential arguments to fix
- [ ] `data_dir` `Default=None`

[nilearn/datasets/neurovault.py::fetch_neurovault_motor_task - **line: 2835**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/neurovault.py#L2835)
<br>Potential arguments to fix
- [ ] `data_dir` `Default=None`

[nilearn/datasets/neurovault.py::fetch_neurovault_auditory_computation_task - **line: 2878**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/neurovault.py#L2878)
<br>Potential arguments to fix
- [ ] `data_dir` `Default=None`

## [nilearn/datasets/func.py](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py)
[nilearn/datasets/func.py::fetch_localizer_contrasts - **line: 536**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py#L536)
<br>Potential arguments to fix
- [ ] `n_subjects` `Default=None`

[nilearn/datasets/func.py::fetch_abide_pcp - **line: 1006**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py#L1006)
<br>Potential arguments to fix
- [ ] `derivatives` `Default=None`
- [ ] `n_subjects` `Default=None`

[nilearn/datasets/func.py::fetch_development_fmri - **line: 1956**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py#L1956)
<br>Potential arguments to fix
- [ ] `n_subjects` `Default=None`

[nilearn/datasets/func.py::fetch_language_localizer_demo_dataset - **line: 2172**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py#L2172)
<br>Potential arguments to fix
- [ ] `legacy_output` `Default=True`

[nilearn/datasets/func.py::fetch_openneuro_dataset_index - **line: 2310**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py#L2310)
<br>Potential arguments to fix
- [ ] `verbose` `Default=1`

[nilearn/datasets/func.py::select_from_index - **line: 2422**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py#L2422)
<br>Potential arguments to fix
- [ ] `n_subjects` `Default=None`
- [ ] `exclusion_filters` `Default=None`
- [ ] `inclusion_filters` `Default=None`

[nilearn/datasets/func.py::fetch_openneuro_dataset - **line: 2527**](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/func.py#L2527)
<br>Potential arguments to fix
- [ ] `urls` `Default=None`

## [nilearn/image/resampling.py](https://github.com/nilearn/nilearn/blob/main/nilearn/image/resampling.py)
[nilearn/image/resampling.py::resample_img - **line: 349**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/resampling.py#L349)
<br>Potential arguments to fix
- [ ] `copy_header` `Default=False`
- [ ] `target_shape` `Default=None`
- [ ] `target_affine` `Default=None`

[nilearn/image/resampling.py::resample_to_img - **line: 721**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/resampling.py#L721)
<br>Potential arguments to fix
- [ ] `order` `Default='F'`

[nilearn/image/resampling.py::reorder_img - **line: 817**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/resampling.py#L817)
<br>Potential arguments to fix
- [ ] `copy_header` `Default=False`
- [ ] `resample` `Default=None`

## [nilearn/image/image.py](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py)
[nilearn/image/image.py::high_variance_confounds - **line: 67**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L67)
<br>Potential arguments to fix
- [ ] `mask_img` `Default=None`
- [ ] `percentile` `Default=2.0`

[nilearn/image/image.py::crop_img - **line: 354**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L354)
<br>Potential arguments to fix
- [ ] `rtol` `Default=1e-08`

[nilearn/image/image.py::mean_img - **line: 529**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L529)
<br>Potential arguments to fix
- [ ] `target_shape` `Default=None`
- [ ] `target_affine` `Default=None`

[nilearn/image/image.py::new_img_like - **line: 778**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L778)
<br>Potential arguments to fix
- [ ] `affine` `Default=None`

[nilearn/image/image.py::binarize_img - **line: 1174**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L1174)
<br>Potential arguments to fix
- [ ] `two_sided` `Default=True`
- [ ] `threshold` `Default=0`

[nilearn/image/image.py::clean_img - **line: 1258**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L1258)
<br>Potential arguments to fix
- [ ] `mask_img` `Default=None`
- [ ] `t_r` `Default=None`
- [ ] `high_pass` `Default=None`
- [ ] `low_pass` `Default=None`
- [ ] `confounds` `Default=None`
- [ ] `runs` `Default=None`

[nilearn/image/image.py::load_img - **line: 1434**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L1434)
<br>Potential arguments to fix
- [ ] `dtype` `Default=None`

[nilearn/image/image.py::concat_imgs - **line: 1474**](https://github.com/nilearn/nilearn/blob/main/nilearn/image/image.py#L1474)
<br>Potential arguments to fix
- [ ] `ensure_ndim` `Default=None`

## [nilearn/surface/surface.py](https://github.com/nilearn/nilearn/blob/main/nilearn/surface/surface.py)
[nilearn/surface/surface.py::vol_to_surf - **line: 543**](https://github.com/nilearn/nilearn/blob/main/nilearn/surface/surface.py#L543)
<br>Potential arguments to fix
- [ ] `depth` `Default=None`
- [ ] `inner_mesh` `Default=None`
- [ ] `mask_img` `Default=None`
- [ ] `n_samples` `Default=None`

## [nilearn/decoding/space_net.py](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/space_net.py)
[nilearn/decoding/space_net.py::path_scores - **line: 297**](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/space_net.py#L297)
<br>Potential arguments to fix
- [ ] `screening_percentile` `Default=20.0`
- [ ] `key` `Default=None`
- [ ] `eps` `Default=0.001`

## [nilearn/decoding/space_net_solvers.py](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/space_net_solvers.py)
[nilearn/decoding/space_net_solvers.py::graph_net_squared_loss - **line: 268**](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/space_net_solvers.py#L268)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`
- [ ] `lipschitz_constant` `Default=None`
- [ ] `callback` `Default=None`
- [ ] `tol` `Default=0.0001`
- [ ] `max_iter` `Default=1000`
- [ ] `init` `Default=None`

[nilearn/decoding/space_net_solvers.py::graph_net_logistic - **line: 348**](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/space_net_solvers.py#L348)
<br>Potential arguments to fix
- [ ] `lipschitz_constant` `Default=None`
- [ ] `verbose` `Default=0`
- [ ] `callback` `Default=None`
- [ ] `tol` `Default=0.0001`
- [ ] `max_iter` `Default=1000`
- [ ] `init` `Default=None`

[nilearn/decoding/space_net_solvers.py::tvl1_solver - **line: 478**](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/space_net_solvers.py#L478)
<br>Potential arguments to fix
- [ ] `verbose` `Default=1`
- [ ] `tol` `Default=0.0001`
- [ ] `init` `Default=None`
- [ ] `loss` `Default=None`

## [nilearn/decoding/fista.py](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/fista.py)
[nilearn/decoding/fista.py::mfista - **line: 67**](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/fista.py#L67)
<br>Potential arguments to fix
- [ ] `callback` `Default=None`
- [ ] `dgap_factor` `Default=None`
- [ ] `tol` `Default=0.0001`
- [ ] `init` `Default=None`
- [ ] `dgap_tol` `Default=None`

## [nilearn/decoding/searchlight.py](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/searchlight.py)
[nilearn/decoding/searchlight.py::search_light - **line: 32**](https://github.com/nilearn/nilearn/blob/main/nilearn/decoding/searchlight.py#L32)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`
- [ ] `n_jobs` `Default=-1`
- [ ] `cv` `Default=None`
- [ ] `scoring` `Default=None`

## [nilearn/plotting/cm.py](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/cm.py)
[nilearn/plotting/cm.py::dim_cmap - **line: 317**](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/cm.py#L317)
<br>Potential arguments to fix
- [ ] `to_white` `Default=True`
- [ ] `factor` `Default=0.3`

## [nilearn/plotting/js_plotting_utils.py](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/js_plotting_utils.py)
[nilearn/plotting/js_plotting_utils.py::add_js_lib - **line: 26**](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/js_plotting_utils.py#L26)
<br>Potential arguments to fix
- [ ] `embed_js` `Default=True`

[nilearn/plotting/js_plotting_utils.py::colorscale - **line: 71**](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/js_plotting_utils.py#L71)
<br>Potential arguments to fix
- [ ] `vmin` `Default=None`
- [ ] `vmax` `Default=None`
- [ ] `symmetric_cmap` `Default=True`
- [ ] `threshold` `Default=None`

## [nilearn/regions/region_extractor.py](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/region_extractor.py)
[nilearn/regions/region_extractor.py::connected_regions - **line: 131**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/region_extractor.py#L131)
<br>Potential arguments to fix
- [ ] `mask_img` `Default=None`

[nilearn/regions/region_extractor.py::connected_label_regions - **line: 477**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/region_extractor.py#L477)
<br>Potential arguments to fix
- [ ] `labels` `Default=None`
- [ ] `min_size` `Default=None`

## [nilearn/regions/signal_extraction.py](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/signal_extraction.py)
[nilearn/regions/signal_extraction.py::img_to_signals_labels - **line: 243**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/signal_extraction.py#L243)
<br>Potential arguments to fix
- [ ] `strategy` `Default='mean'`
- [ ] `order` `Default='F'`
- [ ] `mask_img` `Default=None`

[nilearn/regions/signal_extraction.py::signals_to_img_labels - **line: 368**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/signal_extraction.py#L368)
<br>Potential arguments to fix
- [ ] `order` `Default='F'`
- [ ] `mask_img` `Default=None`

[nilearn/regions/signal_extraction.py::img_to_signals_maps - **line: 453**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/signal_extraction.py#L453)
<br>Potential arguments to fix
- [ ] `mask_img` `Default=None`

[nilearn/regions/signal_extraction.py::signals_to_img_maps - **line: 548**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/signal_extraction.py#L548)
<br>Potential arguments to fix
- [ ] `mask_img` `Default=None`

## [nilearn/regions/hierarchical_kmeans_clustering.py](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/hierarchical_kmeans_clustering.py)
[nilearn/regions/hierarchical_kmeans_clustering.py::hierarchical_k_means - **line: 49**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/hierarchical_kmeans_clustering.py#L49)
<br>Potential arguments to fix
- [ ] `random_state` `Default=0`
- [ ] `verbose` `Default=0`

## [nilearn/regions/rena_clustering.py](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/rena_clustering.py)
[nilearn/regions/rena_clustering.py::recursive_neighbor_agglomeration - **line: 365**](https://github.com/nilearn/nilearn/blob/main/nilearn/regions/rena_clustering.py#L365)
<br>Potential arguments to fix
- [ ] `threshold` `Default=1e-07`

## [nilearn/connectome/group_sparse_cov.py](https://github.com/nilearn/nilearn/blob/main/nilearn/connectome/group_sparse_cov.py)
[nilearn/connectome/group_sparse_cov.py::group_sparse_covariance - **line: 132**](https://github.com/nilearn/nilearn/blob/main/nilearn/connectome/group_sparse_cov.py#L132)
<br>Potential arguments to fix
- [ ] `precisions_init` `Default=None`
- [ ] `probe_function` `Default=None`
- [ ] `tol` `Default=0.001`

[nilearn/connectome/group_sparse_cov.py::group_sparse_covariance_path - **line: 783**](https://github.com/nilearn/nilearn/blob/main/nilearn/connectome/group_sparse_cov.py#L783)
<br>Potential arguments to fix
- [ ] `probe_function` `Default=None`
- [ ] `debug` `Default=False`
- [ ] `precisions_init` `Default=None`
- [ ] `max_iter` `Default=10`
- [ ] `tol` `Default=0.001`
- [ ] `test_subjs` `Default=None`

## [nilearn/connectome/connectivity_matrices.py](https://github.com/nilearn/nilearn/blob/main/nilearn/connectome/connectivity_matrices.py)
[nilearn/connectome/connectivity_matrices.py::vec_to_sym_matrix - **line: 248**](https://github.com/nilearn/nilearn/blob/main/nilearn/connectome/connectivity_matrices.py#L248)
<br>Potential arguments to fix
- [ ] `diagonal` `Default=None`

## [nilearn/interfaces/bids/query.py](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/query.py)
[nilearn/interfaces/bids/query.py::infer_slice_timing_start_time_from_dataset - **line: 57**](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/query.py#L57)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`

[nilearn/interfaces/bids/query.py::infer_repetition_time_from_dataset - **line: 109**](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/query.py#L109)
<br>Potential arguments to fix
- [ ] `verbose` `Default=0`

[nilearn/interfaces/bids/query.py::get_bids_files - **line: 157**](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/query.py#L157)
<br>Potential arguments to fix
- [ ] `filters` `Default=None`

## [nilearn/interfaces/bids/glm.py](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/glm.py)
[nilearn/interfaces/bids/glm.py::save_glm_to_bids - **line: 158**](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/glm.py#L158)
<br>Potential arguments to fix
- [ ] `out_dir` `Default='.'`

## [nilearn/interfaces/bids/utils.py](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/utils.py)
[nilearn/interfaces/bids/utils.py::create_bids_filename - **line: 64**](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/bids/utils.py#L64)
<br>Potential arguments to fix
- [ ] `entities_to_include` `Default=None`

## [nilearn/interfaces/fmriprep/load_confounds_strategy.py](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/fmriprep/load_confounds_strategy.py)
[nilearn/interfaces/fmriprep/load_confounds_strategy.py::load_confounds_strategy - **line: 54**](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/fmriprep/load_confounds_strategy.py#L54)
<br>Potential arguments to fix
- [ ] `denoise_strategy` `Default='simple'`

## [nilearn/interfaces/fmriprep/load_confounds.py](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/fmriprep/load_confounds.py)
[nilearn/interfaces/fmriprep/load_confounds.py::load_confounds - **line: 95**](https://github.com/nilearn/nilearn/blob/main/nilearn/interfaces/fmriprep/load_confounds.py#L95)
<br>Potential arguments to fix
- [ ] `ica_aroma` `Default='full'`
- [ ] `n_compcor` `Default='all'`
- [ ] `compcor` `Default='anat_combined'`
- [ ] `global_signal` `Default='basic'`
- [ ] `wm_csf` `Default='basic'`
- [ ] `motion` `Default='full'`
- [ ] `strategy` `Default=('motion', 'high_pass', 'wm_csf')`

**Comment by bthirion** [comment]
Thx ! The list is impressive...

**Comment by Remi-Gau** [comment]
Updated the script to skip test files

**Comment by anupriyakkumari** [comment]
Hi, is this issue available to work on? I would like to take it up.

**Comment by Remi-Gau** [comment]
> Hi, is this issue available to work on? I would like to take it up.

hey @anupriyakkumari 
No one has started to work on this yet.

I would reommend you start small: pick one module (for example nilearn/glm/first_level/first_level.py) or a subpackage (nilearn/glm/first_level), fix the issues in it and then open a PR for this.

This will make re review process easier and faster.

**Comment by Remi-Gau** [comment]
also let me know which part you are planning to work on, so I can coordinate work load if some people want to start working on this too.

**Comment by Remi-Gau** [comment]
will update the listing of things to fix as it seems to include some private functions that are not the most urgent to document.

**Comment by anupriyakkumari** [comment]
Hi, @Remi-Gau, I took a look at the module you suggested, `nilearn/glm/first_level/first_level.py,` and observed that all the docstring default values there are fixed and match the ones generated by the script https://github.com/nilearn/nilearn_sandbox/pull/12.

I wish to confirm if I, therefore, understand the task correctly - Check whether the default values are correct in the docstrings, and if not, correct them (or add them).

**Comment by Remi-Gau** [comment]
Ok. I have checked a few functions and it seems you are correct. Need to double check what that script is doing.
Will ping you when I have an update.

**Comment by anupriyakkumari** [comment]
Hi @Remi-Gau Any updates on this issue?

**Comment by Remi-Gau** [comment]
Will check the script we use and update.

**Comment by Remi-Gau** [comment]
@bthirion @anupriyakkumari 
The list of TODOs has been updated.
'Fewer' things to do though the list is still quite long

**Comment by anupriyakkumari** [comment]
Hi @Remi-Gau. Thanks a lot for updating the list. I have been caught up with some work. I think I can wrap up `nilearn/glm` entirely in one sprint. Maybe split that into `nilearn/glm/first_level`, `nilearn/glm/second_level` and then the remaining modules in 3 PRs?

**Comment by Remi-Gau** [comment]
That'd be great. 
Do things at your own pace, no problem.
Just make sure you check the doc string of the functions you will update.
I remember that some lack some of their parameter description on purpose: see for example
https://github.com/nilearn/nilearn/blob/89b91df4a9b6c482ec6f3bc17a6c9fa53d4bfad8/nilearn/glm/first_level/first_level.py#L1284
