### ISSUE TITLE
Possible "infra" improvements as recommend by scientific-python

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4003]
https://learn.scientific-python.org/development/guides/repo-review/?repo=nilearn%2Fnilearn&branch=main

A few of those changes should be pretty easy and straightforward: I can take care of them if no one is opposed.

**Comment by Remi-Gau** [comment]
# TODO

Selecting those that are easy / relevant:

### Pytest

- [ ] set xfail_strict to true as we do have a few xfail tests
- [ ] use --strict-config
- [ ] use --strict-markers
- [ ] use -ra 

GitHub Actions

- [ ] All workflows should have a nice readable name: https://learn.scientific-python.org/development/guides/gha-basic#GH101

Pre-commit

- [ ] change repo for black to: https://github.com/psf/black-pre-commit-mirror
- [ ] use prettier for json formatting: https://github.com/pre-commit/mirrors-prettier (yaml is already taken care of)
- [ ] Use blacken-docs
