### ISSUE TITLE
Move experimental Surface related API into stable codebase

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4568]
- [x] move and rename pytest fixture from experimental/conftest.py - see #4638 
- [x] Update experimental surface example
  - [x] plot_surf_atlas - #4678
  - [x] plot_localizer_surface_analysis - #4681
  - [x] plot_3d_map_to_surface_projection - #4674
  - [x] plot_surface_bids_analysis - #4682
  - [x] plot_surface_image_and_maskers - #4684
  - [x] plot_surf_stat_map - #4683
- [ ] Move modules:
  - [x] IO functions - #4685
  - [x] plotting functions - #4688  
  - [x] maskers - #4692
  - [x] label masker #4714 
  - [ ] datasets - #4693 
  - [x] surface - #4723
- [ ] Check public class/method and function names
- [ ] Update doc/modules/surface.rst and remove experimental.rst
- [ ] Increase testing
- [x] What to deprecate from old surface.py API?
- [ ] Check/improve docstrings (still need review of course)

**Comment by Remi-Gau** [comment]
````
$ find nilearn -name '*.py' -exec grep -H "nilearn.experimental" {} \;

nilearn/experimental/plotting/_surface_plotting.py:from nilearn.experimental.surface import PolyMesh, SurfaceImage
nilearn/experimental/plotting/tests/test_surface_plotting.py:from nilearn.experimental.plotting._surface_plotting import _check_inputs
nilearn/experimental/conftest.py:from nilearn.experimental.surface import (
nilearn/experimental/reporting/tests/test_html_report.py:from nilearn.experimental.conftest import return_mini_binary_mask
nilearn/experimental/reporting/tests/test_html_report.py:from nilearn.experimental.surface import SurfaceLabelsMasker, SurfaceMasker
nilearn/experimental/__init__.py:"""The :mod:`nilearn.experimental` module provides importable modules that \
nilearn/experimental/__init__.py:    All features in the ``nilearn.experimental`` module
nilearn/experimental/surface/maskers.py:from nilearn.experimental.surface._surface_image import PolyMesh, SurfaceImage
nilearn/experimental/surface/maskers.py:        from nilearn.experimental import plotting
nilearn/experimental/surface/maskers.py:        from nilearn.experimental import plotting
nilearn/experimental/surface/tests/test_io.py:from nilearn.experimental.surface import _io
nilearn/experimental/surface/tests/test_datasets.py:from nilearn.experimental.surface import (
nilearn/experimental/surface/tests/test_maskers.py:from nilearn.experimental.surface import (
nilearn/experimental/surface/tests/test_surface_image.py:from nilearn.experimental.surface import FileMesh, InMemoryMesh, SurfaceImage
nilearn/experimental/surface/_surface_image.py:from nilearn.experimental.surface import _io
nilearn/experimental/surface/_datasets.py:from nilearn.experimental.surface import _io
nilearn/experimental/surface/_datasets.py:from nilearn.experimental.surface._surface_image import (
nilearn/experimental/surface/__init__.py:"""The :mod:`nilearn.experimental.surface` module."""
nilearn/experimental/surface/__init__.py:from nilearn.experimental.surface._datasets import (
nilearn/experimental/surface/__init__.py:from nilearn.experimental.surface._surface_image import (
nilearn/experimental/surface/__init__.py:from nilearn.experimental.surface.maskers import (
nilearn/_utils/tests/test_masker_validation.py:from nilearn.experimental.surface import SurfaceMasker
nilearn/_utils/masker_validation.py:from nilearn.experimental.surface import SurfaceMasker
nilearn/decoding/tests/test_decoder.py:from nilearn.experimental.surface import SurfaceMasker
nilearn/decoding/space_net.py:from nilearn.experimental.surface import SurfaceMasker
nilearn/decoding/decoder.py:from nilearn.experimental.surface import SurfaceMasker
nilearn/glm/tests/test_first_level.py:from nilearn.experimental.surface import SurfaceImage, SurfaceMasker
nilearn/glm/first_level/first_level.py:from nilearn.experimental.surface import SurfaceImage, SurfaceMasker
nilearn/conftest.py:from nilearn.experimental.conftest import (  # noqa: F401
nilearn/reporting/glm_reporter.py:from nilearn.experimental.surface import SurfaceMasker
````

**Comment by Remi-Gau** [comment]
Regarding  deprecation of the old API it seems that quite a few things that are in the init of our current surface module are not part of the doc of the public API in terms of what is in the doc.

https://github.com/nilearn/nilearn/blob/f5114ee0b831530907e554a669427e70837029d2/nilearn/surface/__init__.py#L3

**Comment by Remi-Gau** [comment]
> * What to deprecate from old surface.py API?

nothing at the moment: will happen later
