### ISSUE TITLE
[META] surface roadmap

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4889]
Meta issues to list and discuss what to do next for the Surface API.

> [!IMPORTANT]  
> See also this Github project / Kanban: https://github.com/orgs/nilearn/projects/4 

## Refactor
- [ ] refactor fixtures

## Enhancements
- utility functions (see volume counter part in nilearn.image)
  - [ ] mean surface images
  - [ ] concatenate images
  - [ ] generator to iterate over 'timepoints' for 2D surface image
  - [ ] new_img_like
  - [ ] perform some math on surface images
  - [ ] mask image manipulation: intersection...

## Examples
- use more meaningful decoding examples
- better dataset for surface example

## Documentation
- [ ] expand user guide
- [ ] include about using the right space when projecting to surface
